### ISSUE TITLE
Web Request Tracking is not working

### ISSUE THREAD

**Issue by doraair** [davidjrh/dnn.appinsights#10]
Reference to https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/569 We need TelemetryCorrelationHttpModule config for Web Request Tracking

We need to modify 2 files 
- web.install.config
Adding these at line:5
`      <add xdt:Transform="Remove" xdt:Locator="Condition(@name='TelemetryCorrelationHttpModule')" />
      <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="managedHandler" xdt:Transform="Insert" />
`
- web.uninstall.config 
Adding these at line:5

`      <add xdt:Transform="Remove" xdt:Locator="Condition(@name='TelemetryCorrelationHttpModule')" />
`

**Comment by davidjrh** [comment]
Thanks! I have added the suggested fix, plus the dependant assemblies that were not being included in the package.
