### ISSUE TITLE
Module won't load in DNN 9.3.2

### ISSUE THREAD

**Issue by itzmesaran** [davidjrh/dnn.appinsights#12]
Could you please update the module for DNN 9.3.2 and make it compatible?

Here is the error from browser console:
Uncaught TypeError: Cannot read property 'func' of undefined
    at Object.<anonymous> (<anonymous>:1:8937)
    at Object.<anonymous> (<anonymous>:1:9084)
    at t (<anonymous>:1:107)
    at Object.<anonymous> (<anonymous>:1:10851)
    at Object.<anonymous> (<anonymous>:1:11157)
    at t (<anonymous>:1:107)
    at Object.<anonymous> (<anonymous>:1:9837)
    at Object.<anonymous> (<anonymous>:1:9845)
    at t (<anonymous>:1:107)
    at Object.<anonymous> (<anonymous>:1:619)

**Comment by davidjrh** [comment]
Hi @itzmesaran, 

You are right, on DNN 9.3 breaking changes on the DNN Persona Bar were introduced, and I haven't had time to upgrade this module (and the others I maintain: Redis and Azure AD). 

The steps to do it are mentioned on this post (https://www.dnnsoftware.com/community-blog/cid/156674/upgrading-persona-bar-components-for-dnn-93). I will be travelling for the next two weeks with no time to do it, so meanwhile, if someone do a pull request I will try to find time to merge it.

**Comment by itzmesaran** [comment]
@davidjrh i wish i can, i'm currently tied up on a time sensitive project until August. I'll look to see if someone from dnn community chime in or when you get back from your travel. Take care.

**Comment by davidjrh** [comment]
Hi @itzmesaran I have released a new version with 9.3.x compatibility. https://github.com/davidjrh/dnn.appinsights/releases/tag/v3.1.0
