### ISSUE TITLE
Javascript error in 9.6

### ISSUE THREAD

**Issue by Jo-Hacker** [davidjrh/dnn.appinsights#23]
Hi,

I've installed this on a DNN 9.6.1 installation running on an Azure app service but when I open the settings page from the persona bar, I get a blank page and an error in the JS console - Uncaught TypeError: Cannot read property 'func' of undefined

Jo

**Comment by davidjrh** [comment]
Hi @Jo-Hacker, I'm running several websites on Azure and working well. I've just installed on a 9.9.1 and no javascript issues. Please, confirm if this is still an issue to reopen it.
