### ISSUE TITLE
Looking for missing npm packages to compile version 3.0.1

### ISSUE THREAD

**Issue by okashina** [davidjrh/dnn.appinsights#37]
I was trying to build version 3.0.1 and two of the npm packages are not available any where. I was wondering if someone has the following packages they could give me or location of where I can download them: 

- "dnn-webpack-externals": "^1.0.9"
- "dnn-global-styles": "0.0.5"

Thank you in advance.

**Comment by davidjrh** [comment]
Hi @okashina those packages disappeared from npm. What we've done to solve it on this latest release, is to host them in a public feed at Intelequia (see https://github.com/davidjrh/dnn.appinsights/blob/master/AppInsightsProvider/AppInsights.Web/.npmrc)
