### ISSUE TITLE
After install of 2.1.0 no live metric stream in Azure AI

### ISSUE THREAD

**Issue by kingjordan** [davidjrh/dnn.appinsights#5]
Hello,

I installed the 2.1 version and attempted to view the live metic data from application insight.  I get the following message when I open the tile:

> Not available: your app is offline or using an older SDK

And then a demo is displayed below this error.  

Were you able to get the live metrics stream to show for your apps?

Thanks,

great module!

**Comment by davidjrh** [comment]
The Live Stream metrics comes with Application Insights 2.1.0 or higher, but the current version of the provider is targeting an older nuget package. I'm going to upgrade the packages and also prepare it for DNN 9.x allowing to configure it through the Persona Bar. Working on it right now.

**Comment by kingjordan** [comment]
Awesome, thanks david, this is a module that I put on all my azure web apps!

**Comment by davidjrh** [comment]
This has been completed (AI 2.4 and persona bar implementation) on 3.0 release.
