### ISSUE TITLE
Menu option sill resided on the Admin menu

### ISSUE THREAD

**Issue by leigh-pointer** [davidjrh/dnn.appinsights#7]
3,0,0 install upgraded from 2,1 - 2,4
/Host/Application-Insights/portalid/0

![image](https://user-images.githubusercontent.com/9447612/29248123-fd09b16a-800f-11e7-872e-4f353cf4d25b.png)

**Comment by davidjrh** [comment]
Fixed on commit https://github.com/davidjrh/dnn.appinsights/commit/b653d389ee7c807dee1b79ce040b4fa1d57bdc4f
